# SPDX-FileCopyrightText: 2019 Bitcoin Suisse
#
# SPDX-License-Identifier: LicenseRef-MIT-BitcoinSuisse
#
# when updating git dependencies, please run
# nix run -f https://github.com/serokell/scratch/archive/master.tar.gz scripts.update-stack-shas -c update-stack-shas
resolver: lts-16.5

packages:
- .

extra-deps:
- git:
    https://gitlab.com/morley-framework/morley.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    8e6568b0f0839b0dd9c0e99a3a299be4627aece8 # morley-1.10
  subdirs:
    - code/morley-multisig
    - code/morley-client
    - code/cleveland

- git:
    https://gitlab.com/morley-framework/morley-ledgers.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    6a3bc286a356ce3b46269fdc5157b8a4db694c76 # TODO: not master
  subdirs:
    - code/morley-ledgers
    - code/morley-ledgers-test

- git:
    https://gitlab.com/morley-framework/morley-upgradeable.git
    # ^ CI cannot use ssh, so we use http clone here
  commit:
    75e8cc24880b1887bcfe296199ad7c7fde6a604d # TODO not master

- git:
    https://gitlab.com/morley-framework/indigo.git # CI can't use SSH
  commit:
    db0361cc61eca490222ed10bd139ce2de3a0c3fe # TODO not master

# Stable parts of morley available from Hackage
- morley-prelude-0.3.0
- tasty-hunit-compat-0.2
- morley-1.10.0
- lorentz-0.8.0

# Required by morley
- show-type-0.1.1@sha256:24f681a3481b3f9630e619d816054804ba1bd6cc05b5978ddd2cece8499ff2fa
- base58-bytestring-0.1.0
- hex-text-0.1.0.0
- named-0.3.0.1@sha256:69b9722301201f8ed8abc89c4595e22c746e944bf4cdfafa8b21b14d336b26d1,2233
- vinyl-0.12.1@sha256:43456d4b3009646eee63953cbe539f1f4d0caf8bc3c25e841117e712836508f3,3790
- cryptonite-0.27
- git: https://github.com/int-index/caps.git
  commit: c5d61837eb358989b581ed82b1e79158c4823b1b
- uncaught-exception-0.1.0
